m_mainactivity:
    path:     /
    defaults: { _controller: MBundle:MainActivity:index }
    
m_index:
    path:     /index
    defaults: { _controller: MBundle:Default:index }
    
m_message_index:
    path:     /message/index
    defaults: { _controller: MBundle:Message:index }
